@startuml scheme
entity user {
  * id: serial
  --
  * username: text
  * password: text
  * created_at: timestamp
}

entity gallery {
  * id: serial
  --
  * user_id: unsigned bigint
  * name: text
  * description: text
  * created_at: timestamp
}

entity image {
  * id: serial
  --
  * gallery_id: unsigned bigint
  * reference: text
  * description: text
  * created_at: timestamp
}

entity comment{
  * id: serial
  --
  * image_id: unsigned bigint
  * user_id: unsigned bigint
  * title: text
  * content: text
  * created_at: timestamp
}


user    --|{ gallery
user    --|{ comment
gallery --|{ image
image   --|{ comment

@enduml